services:
  http-app-server:
    build:
      dockerfile: docker/golang/dev.Dockerfile
      context: .
    networks:
      - http-app-network
    ports:
      - "8080:8080"
      - "8081:8081"
    expose:
      - "8080"
      - "8081"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - keydb

  postgres:
    image: postgres:latest
    command: -c 'log_min_messages=debug5'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - http-app-network
    env_file:
      - .env

  keydb:
    image: eqalpha/keydb:latest
    command: keydb-server /etc/keydb/keydb.conf
    volumes:
      - keydb:/data
    ports:
      - "6379:6379"
    networks:
      - http-app-network

networks:
  http-app-network:
    driver: bridge

volumes:
  postgres:
  keydb: